server:
  port: 8858
spring:
  application:
    name: coin-common
  datasource:
    url: jdbc:mysql://localhost:3306/coin-exchange?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
      config:
        enabled: false
      sentinel:
        transport:
          dashboard: sentinel-dashboard:8080
  redis:
    host: localhost
    port: 6379
swagger2:
  basePackage: com.hzj.controller
  name: 358067067
  url: https://github.com/358067067
  email: xxhundan@qq.com
  title: common
  description: common
  version: 2.0
  termsOfServiceUrl: www.hzj.com
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local: #本地缓存实现
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote: #远端缓存实现(redis)
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}

