server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
    # 网关 + API限流
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            serverAddr: localhost:8848
            dataId: gw-flow
            ruleType: gw_flow
        ds2:
          nacos:
            serverAddr: localhost:8848
            dataId: api-group
            ruleType: gw_api_group
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #配置路由大小写
      routes:
        - id: admin-service_router
          uri: lb://admin-service #转发到服务
          predicates:
            - Path=/admin/** #请求url
